columns:
  - id
  - Gender
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Vehicle_Age
  - Vehicle_Damage
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  - Response


numerical_columns:
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  # - Response

categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage
  - Response

drop_columns: _id

# for data transformation
num_features:
  - Age
  - Vintage


mm_columns:
  - Annual_Premium